# Copyright (C) 2019-2025 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/blackberry/luna/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/blackberry/luna

PRODUCT_COPY_FILES += \
    vendor/blackberry/luna/proprietary/vendor/etc/acdbdata/MTP/sdm660-snd-card-bbe100/bb_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/sdm660-snd-card-bbe100/bb_Bluetooth_cal.acdb \
    vendor/blackberry/luna/proprietary/vendor/etc/acdbdata/MTP/sdm660-snd-card-bbe100/bb_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/sdm660-snd-card-bbe100/bb_General_cal.acdb \
    vendor/blackberry/luna/proprietary/vendor/etc/acdbdata/MTP/sdm660-snd-card-bbe100/bb_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/sdm660-snd-card-bbe100/bb_Global_cal.acdb \
    vendor/blackberry/luna/proprietary/vendor/etc/acdbdata/MTP/sdm660-snd-card-bbe100/bb_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/sdm660-snd-card-bbe100/bb_Handset_cal.acdb \
    vendor/blackberry/luna/proprietary/vendor/etc/acdbdata/MTP/sdm660-snd-card-bbe100/bb_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/sdm660-snd-card-bbe100/bb_Hdmi_cal.acdb \
    vendor/blackberry/luna/proprietary/vendor/etc/acdbdata/MTP/sdm660-snd-card-bbe100/bb_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/sdm660-snd-card-bbe100/bb_Headset_cal.acdb \
    vendor/blackberry/luna/proprietary/vendor/etc/acdbdata/MTP/sdm660-snd-card-bbe100/bb_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/sdm660-snd-card-bbe100/bb_Speaker_cal.acdb \
    vendor/blackberry/luna/proprietary/vendor/etc/camera/ov5675_luna_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov5675_luna_chromatix.xml \
    vendor/blackberry/luna/proprietary/vendor/etc/camera/s5k3l8_luna_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3l8_luna_chromatix.xml \
    vendor/blackberry/luna/proprietary/vendor/etc/camera/s5k4h7_luna_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k4h7_luna_chromatix.xml \
    vendor/blackberry/luna/proprietary/vendor/etc/mixer_paths_bbe100.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_bbe100.xml \
    vendor/blackberry/luna/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/blackberry/luna/proprietary/vendor/firmware/a512_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b01 \
    vendor/blackberry/luna/proprietary/vendor/firmware/a512_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.mdt \
    vendor/blackberry/luna/proprietary/vendor/lib/libactuator_bu64297gwz_luna.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_bu64297gwz_luna.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_a3_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_a3_default_preview.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_a3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_a3_default_video.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_a3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_a3_hfr_120.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_a3_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_a3_hfr_60.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_a3_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_a3_hfr_90.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_common.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_cpp_ds_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_cpp_ds_chromatix.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_cpp_hfr_120.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_cpp_hfr_60.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_cpp_hfr_90.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_cpp_liveshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_cpp_preview.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_cpp_snapshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_cpp_us_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_cpp_us_chromatix.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_cpp_video.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_cpp_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_cpp_video_full.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_default_video.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_hfr_120.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_hfr_60.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_hfr_90.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_liveshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_postproc.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_preview.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_snapshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_video_full.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_zsl_preview.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_ov5675_luna_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5675_luna_zsl_video.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_common.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_cpp_hfr_120.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_cpp_hfr_60.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_cpp_hfr_90.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_cpp_liveshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_cpp_preview.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_cpp_snapshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_cpp_video.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_default_preview_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_default_preview_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_default_video.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_default_video_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_default_video_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_common.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_cpp_hfr_120.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_cpp_hfr_60.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_cpp_hfr_90.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_cpp_liveshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_cpp_preview.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_cpp_snapshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_cpp_video.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_default_preview_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_default_preview_dw9763.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_default_video.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_default_video_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_default_video_dw9763.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_hfr_120.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_hfr_120_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_hfr_120_dw9763.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_hfr_60.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_hfr_60_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_hfr_60_dw9763.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_hfr_90.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_hfr_90_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_hfr_90_dw9763.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_liveshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_postproc.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_preview.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_snapshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_zsl_preview_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_zsl_preview_dw9763.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_f3l8yam_zsl_video_dw9763.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_f3l8yam_zsl_video_dw9763.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_hfr_120.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_hfr_120_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_hfr_120_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_hfr_60.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_hfr_60_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_hfr_60_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_hfr_90.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_hfr_90_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_hfr_90_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_common.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_cpp_hfr_120.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_cpp_hfr_60.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_cpp_hfr_90.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_cpp_liveshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_cpp_multi_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_cpp_multi_snapshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_cpp_preview.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_cpp_snapshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_cpp_video.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_default_preview_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_default_preview_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_default_video.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_default_video_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_default_video_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_hfr_120.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_hfr_120_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_hfr_120_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_hfr_60.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_hfr_60_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_hfr_60_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_hfr_90.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_hfr_90_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_hfr_90_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_postproc.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_preview.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_snapshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_zsl_preview_bu64297gwz.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_zsl_preview_bu64297gwz.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_luna_zsl_video_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_luna_zsl_video_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_common.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_cpp_hfr_120.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_cpp_hfr_60.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_cpp_hfr_90.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_cpp_liveshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_cpp_preview.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_cpp_snapshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_cpp_video.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_default_preview_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_default_preview_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_default_video.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_default_video_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_default_video_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_hfr_120.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_hfr_120_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_hfr_120_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_hfr_60.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_hfr_60_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_hfr_60_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_hfr_90.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_hfr_90_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_hfr_90_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_postproc.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_preview.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_snapshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_zsl_preview_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_zsl_preview_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_mono_zsl_video_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_mono_zsl_video_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_postproc.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_preview.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_snapshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_zsl_preview_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_zsl_preview_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k3l8_zsl_video_ak7345.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_zsl_video_ak7345.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_1080p_preview_ad5816g.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_1080p_preview_ad5816g.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_1080p_video_ad5816g.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_1080p_video_ad5816g.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_4k_preview_ad5816g.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_4k_preview_ad5816g.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_4k_video_ad5816g.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_4k_video_ad5816g.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_common.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_cpp_hfr_120.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_cpp_hfr_60.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_cpp_hfr_90.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_cpp_liveshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_cpp_preview.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_cpp_snapshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_cpp_snapshot_downscale.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_cpp_snapshot_downscale.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_cpp_snapshot_upscale.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_cpp_snapshot_upscale.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_cpp_video.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_cpp_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_cpp_video_4k.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_default_preview_ad5816g.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_default_preview_ad5816g.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_default_video.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_default_video_ad5816g.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_default_video_ad5816g.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_hfr_120.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_hfr_120_ad5816g.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_hfr_120_ad5816g.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_hfr_60.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_hfr_60_ad5816g.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_hfr_60_ad5816g.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_hfr_90.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_hfr_90_ad5816g.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_hfr_90_ad5816g.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_liveshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_postproc.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_preview.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_snapshot.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_video_4k.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_zsl_preview_ad5816g.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_zsl_preview_ad5816g.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libchromatix_s5k4h7_luna_zsl_video_ad5816g.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h7_luna_zsl_video_ad5816g.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libmmcamera_ov5675_luna.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov5675_luna.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libmmcamera_ov5675_luna_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov5675_luna_eeprom.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libmmcamera_s5k3l8.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3l8.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libmmcamera_s5k3l8_luna.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3l8_luna.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libmmcamera_s5k3l8_luna_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3l8_luna_eeprom.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libmmcamera_s5k3l8_mono.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3l8_mono.so \
    vendor/blackberry/luna/proprietary/vendor/lib/libmmcamera_s5k4h7_luna.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k4h7_luna.so
